# Generated by Django 5.0.1 on 2024-01-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdetails',
            name='HR_module_completed',
            field=models.CharField(blank=True, choices=[('', ''), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=100, null=True, verbose_name='Has the HR module been completed or not completed?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='RR_module_completed',
            field=models.CharField(blank=True, choices=[('', ''), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=100, null=True, verbose_name='Has the RR module been completed or not completed?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='attempt1_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time of 1st attempt to surver RR'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='attempt2_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time of 2nd attempt to surver RR'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='attempt3_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time of 3rd attempt to surver RR'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Record any other comment on the household/interview'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='if_CR_eligible_completed',
            field=models.CharField(blank=True, choices=[('', ''), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=100, null=True, verbose_name='If eligible, has the CR module been completed or not completed?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='if_WER_eligible',
            field=models.CharField(blank=True, choices=[('', ''), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], max_length=100, null=True, verbose_name='If RR household was surveyed, was the household eligible for the WER module'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='if_WER_eligible_coompleted',
            field=models.CharField(blank=True, choices=[('', ''), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=100, null=True, verbose_name='If eligible, has the WER module been completed or not completed?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='if_rr_not_details',
            field=models.TextField(blank=True, null=True, verbose_name='If attempts to survey the RR in their original/current household were not successful, Please record in detail the outcome from the attempts made to interview RR1 '),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='if_rr_surveyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='if RR was surveyed,record the date of interview'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='status_of_RR1',
            field=models.CharField(blank=True, choices=[('', ''), ('Approved', 'Approved '), ('Not Approved', 'Not Approved')], max_length=100, null=True, verbose_name='Status of RR1 Respondent Replacement approval [Based on feedback from column R]'),
        ),
    ]
