# Generated by Django 5.0.1 on 2024-01-18 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdetails',
            name='CR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AddField(
            model_name='trackingdetails',
            name='HR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AddField(
            model_name='trackingdetails',
            name='RR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AddField(
            model_name='trackingdetails',
            name='WER_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor username')),
                ('coordinator', models.CharField(max_length=100, verbose_name='Coordinator username')),
                ('image', models.ImageField(default='user.png', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
