# Generated by Django 5.0.1 on 2024-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0002_trackingdetails_cr_accompanied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
