# Generated by Django 5.0.1 on 2024-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0003_profile_is_coordinator_profile_is_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coordinator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordinator username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor username'),
        ),
    ]
