# Generated by Django 4.2.5 on 2024-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0004_alter_profile_coordinator_alter_profile_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdetails',
            name='CR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied'), ('Not Accompanied', 'Not Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='HR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied'), ('Not Accompanied', 'Not Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='RR_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied'), ('Not Accompanied', 'Not Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
        migrations.AlterField(
            model_name='trackingdetails',
            name='WER_accompanied',
            field=models.CharField(blank=True, choices=[('', ''), ('Partially Accompanied', 'Partially Accompanied'), ('Fully Accompanied', 'Fully Accompanied'), ('Not Accompanied', 'Not Accompanied')], max_length=100, null=True, verbose_name='Were you accompanied by the supervisor?'),
        ),
    ]
