# Generated by Django 4.2.5 on 2024-01-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker_info', '0005_alter_trackingdetails_cr_accompanied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='profile',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_FC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_name', to='tracker_info.supervisors', verbose_name="supervisor's Name"),
        ),
        migrations.AddField(
            model_name='supervisors',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisors',
            name='fc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_username', to=settings.AUTH_USER_MODEL, verbose_name='field coordinator'),
        ),
        migrations.AddField(
            model_name='supervisors',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Region Name'),
        ),
    ]
