# Generated by Django 4.2.5 on 2024-03-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_info', '0006_remove_profile_coordinator_remove_profile_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisors',
            options={'verbose_name': "Surpervisor's Region", 'verbose_name_plural': "Surpervisor's Region"},
        ),
        migrations.AlterModelOptions(
            name='trackingdetails',
            options={'verbose_name': 'Record'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_name', to='tracker_info.supervisors', verbose_name='Region'),
        ),
    ]
